In [1]:
from postprocessing import fabric_api
fabric_api.init("mc_mitdwh/tf_dictionary.pkl", "mc_mitdwh/", "mc_mitdwh/model.h5", "mc_mitdwh/ae/")

/Users/ra-mit/development/fabric/postprocessing/fabric_api.py:53: SyntaxWarning: name 'location_dic' is assigned to before global declaration
  global location_dic
/Users/ra-mit/development/fabric/postprocessing/fabric_api.py:55: SyntaxWarning: name 'inv_location_dic' is assigned to before global declaration
  global inv_location_dic
Using TensorFlow backend.
/Users/ra-mit/development/virtualenvs/fabric/lib/python3.5/site-packages/keras/models.py:240: UserWarning: No training configuration found in save file: the model was *not* compiled. Compile it manually.
  warnings.warn('No training configuration found in save file: '


##### examples
res = fabric_api.where_is("query string")

encoded = fabric_api.encode_query("madden")

decode = fabric_api.decode_query(encoded)

fabric_api.inv_location_dic

In [3]:
fabric_api.where_is("department name school code ocean engineering")

1/1 [==============================] - 0s


(array([0]), '/Users/ra-mit/data/mitdwhdata/Sis_subject_code.csv')

In [4]:
fabric_api.where_is_rank("department name school code ocean engineering")

1/1 [==============================] - 0s


array([[ 0.54028267,  0.0468541 ,  0.32570776,  0.0289434 ,  0.0582121 ]], dtype=float32)

In [35]:
encode = fabric_api.encode_query("madden srmadden madden@csail.mit.edu")
decode, reconst_query = fabric_api.decode_query(encode, threshold=0.6)
reconst_query

'date load key warehouse'

In [53]:
encode_madden = fabric_api.encode_query("madden")
encode_random = fabric_api.encode_query("mit building")

In [54]:
from scipy.spatial.distance import cosine
cosine(encode_madden[0], encode_random[0])

0.00013453087194237323

In [6]:
len(encode[0])

64

In [10]:
decode, reconstructured_query = fabric_api.decode_query(encode)

In [11]:
reconstructured_query

'department course code date load key warehouse'

## TEST

In [14]:
import numpy as np
from sklearn.metrics.pairwise import cosine_similarity
from sklearn.metrics.pairwise import euclidean_distances

In [20]:
a = np.asarray([1,1,1,1,1])
b = np.asarray([10,10,1,1,1])
euclidean_distances(a,b)

/Users/ra-mit/development/virtualenvs/fabric/lib/python3.5/site-packages/sklearn/utils/validation.py:395: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and will raise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  DeprecationWarning)
/Users/ra-mit/development/virtualenvs/fabric/lib/python3.5/site-packages/sklearn/utils/validation.py:395: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and will raise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  DeprecationWarning)


array([[ 12.72792206]])